spring:
  application:
    name: archival-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "optional:classpath:application-secrets.yml"

